
services:
  backendapi:
    image: exnodebackapi6
    container_name: exnodebackapi_6
    hostname: exnodebackapi_6
    ports:
      - "3000:3000" #kong will use 3000 in compose network
    depends_on:
      - postgres
    networks:
      - my-network
  
  #Modern Performance testing , needs test script
  k6:
    image: grafana/k6:latest
    environment:
      - K6_WEB_DASHBOARD=true
    volumes:
      - ./test/k6scripts:/scripts
    entrypoint: ["k6", "run", "/scripts/test.js"]
    ports:
      - "5665:5665"
    depends_on:
      - backendapi
    networks:
      - my-network

  postgres:
    image: postgres:latest
    container_name: postgres
    environment:
      POSTGRES_USER: testuser
      POSTGRES_PASSWORD: testpassword
      POSTGRES_DB: testdatabase6
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - my-network

  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@pgadmin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "15432:80"
    depends_on:
      - postgres
    networks:
      - my-network

volumes:
  postgres_data:

networks:
  my-network:
    driver: bridge